#!/bin/bash
# desc: insecure way (remote) to create SSHFP records
#
# author: Danny Fullerton - Mantor Organization www.mantor.org
# license: public domain

echo "############################################"
echo "# Should not be used unless you can really #"
echo "# trust your network... but who can?!?     #"
echo "############################################"
echo ""

if [ $# -lt 1 ] || [ "$1" = "-h" ]; then
  echo "Usage: $0 <fully qualified domain names>" >&2
  exit 1
fi
fqdn=$1
 
sigs=`ssh-keyscan -t rsa,dsa,ecdsa,ed25519 $* 2> /dev/null`
if [ $? != 0 ]; then
  echo "Error: ssh-keyscan failed. Check the hostnames." >&2
  exit 1
fi

hash1='sha1'
hash2='sha256' 

while IFS= read -r line; do
  echo $line | grep -E '^#' > /dev/null
  if [ $? -eq 0 ]; then
    continue
  fi

  fqdn=`echo -n $line | awk '{print $1}'`
  case `echo -n $line | awk '{print $2}'` in
    'ssh-rsa')
      algo="1" ;;
    'ssh-dss')
      algo="2" ;;
    'ecdsa-sha2-nistp256')
      algo="3" ;;
    'ssh-ed25519')
      algo="4" ;;
  esac

  for j in `seq 1 2` # hash
  do
    eval "h=\${hash${j}}"
    sshfp=`echo -n $line | awk '{print $3}' | openssl base64 -d -A | openssl dgst -${h} | sed 's/^.* //' | awk '{print $1}' | tr '[a-z]' '[A-Z]'`
    echo "${fqdn}. IN SSHFP $algo ${j} ${sshfp}"
  done

done <<< "$sigs"
