#!/bin/sh
# desc: secure way (locally) to create SSHFP records
#
# author: Danny Fullerton - Mantor Organization www.mantor.org
# license: public domain

if [ $# -ne 1 ] || [ "$1" = "-h" ]
then
  echo "Usage: $0 <fully qualify domain name>" >&2
  exit 1
else
  fqdn=$1
fi
 
cipher1='rsa'
cipher2='dsa'
cipher3='ecdsa'

hash1='sha1'
hash2='sha256' 

for i in `seq 1 3` # cipher
do
  for j in `seq 1 2` # hash
  do
    eval "key_path=/etc/ssh/ssh_host_\${cipher${i}}_key.pub"
    
    if [ -f $key_path ]
    then
      eval "h=\${hash${j}}sum"
      sshfp=`awk '{print $2}' $key_path | base64 -d | $h |awk '{print $1}' | tr '[a-z]' '[A-Z]'`
      echo "${fqdn}. IN SSHFP ${i} ${j} ${sshfp}"
    fi
  done
done  
