#!/bin/bash
# desc: insecure way (remote) to create SSHFP records
#
# author: Danny Fullerton - Mantor Organization www.mantor.org
# license: public domain

echo "####################################################"
echo "Should not be used unless you can really trust your"
echo "network... but who can?!?"
echo "####################################################"

sigs=`ssh-keyscan -t ecdsa,dsa,rsa,ed25519 $* 2> /dev/null`

while IFS= read -r line; do
  echo $line | grep -E '^#' > /dev/null
  if [ $? -eq 0 ]; then
    continue
  fi

  host=`echo -n $line | awk '{print $1}'`
  algo=`echo -n $line | awk '{print $2}'`
  sig_sha1=`echo -n $line | awk '{print $3}' | openssl base64 -d -A | openssl dgst -sha1 -r | awk '{print $1}' | tr '[a-z]' '[A-Z]'`
  sig_sha2=`echo -n $line | awk '{print $3}' | openssl base64 -d -A | openssl dgst -sha256 -r | awk '{print $1}' | tr '[a-z]' '[A-Z]'`

  case "$algo" in
    'ssh-rsa')
      algo="1"
      ;;
    'ssh-dss')
      algo="2"
      ;;
    'ecdsa-sha2-nistp256')
      algo="3"
      ;;
    'ssh-ed25519')
      algo="4"
      ;;
  esac

  echo "${host}. IN SSHFP $algo 1 $sig_sha1"
  echo "${host}. IN SSHFP $algo 2 $sig_sha2"
done <<< "$sigs"
